services:
  - type: web
    name: laravel-landing
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        value: https://laravel-landing.onrender.com
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: your-db-host
      - key: DB_PORT
        value: "5432"
      - key: DB_DATABASE
        value: your-db-name
      - key: DB_USERNAME
        value: your-db-user
      - key: DB_PASSWORD
        sync: false
